#!/usr/bin/env node
const Converter = require("./lib/h2roc");
const Preview = require("ro-crate").Preview;
const HtmlFile = require("ro-crate").HtmlFile;
const fs = require("fs-extra");
const xml2js = require("xml2js");
const path = require("path");
const program = require("commander");

program
  .version("0.1.0")
  .description(
    "Converts an Heurist XML file to an RO Crate and copies data from the --files directory specified"
  )
  .arguments("<i>")
  .option("-c, --config [config]", "Configuration file", "test_data/expert-nation.config.json")
  .option("-d, --domain [domain]", "A prefix for the dataset IDs", "test")
  .option("-o, --out [out]", "Output directory in which to write the new ro-crate", "new_crate")
  .option("-b, --baseCrate [RO-Crate template]", "Basic RO-Crate metadata file into which data should be added", "test_data/template-ro-crate-metadata.json")
  .option("-f, --files [files]", "Data directory from which to copy files", "test_data/files")
  .action((i) => {inputFile = i || "test_data/EN_test_sefton.xml"})
program.parse(process.argv);

const destDir = program.out ;
const filesDir = program.files;
const templateFile = program.baseCrate;
const domain = program.domain;
const configPath = program.config;

async function main() {
    await fs.mkdirp(destDir);
    const data = await fs.readFile(inputFile);
    const crateTemplate = JSON.parse(await fs.readFile(templateFile))
    const hxml = await xml2js.parseStringPromise(data/*, options */)
        .catch(function (err) {
            // Failed
        });
     const converter = new Converter({
        destDir: destDir,
        filesDir: filesDir,
        crateTemplate, crateTemplate,
        hxml: hxml,
        domain: domain,
        configPath: JSON.parse(await fs.readFile(configPath))
    });
    converter.convert();
    fs.writeFileSync(path.join(destDir, "ro-crate-metadata.json"), JSON.stringify(converter.crate.json_ld, null, 2));
    const preview = await new Preview(converter.crate);
    const f = new HtmlFile(preview);
    const html = path.join(destDir, "ro-crate-preview.html");
    fs.writeFileSync(html, await f.render());
}

main();

